# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8fbb64cbdca169be6dfcbb01d601d133401170dfc790cd4979643180b512175063cb9016696e75b72385bf4ecd5ca125da46ca32f23b8fe8e28e6f62f701fc

test:
  secret_key_base: 0471c51dbdfd5c3328b4b01f29a9e4d2eb35f56d05ec5e3567aba27598c851468a1cfcd9b433ec6607a666fef2e256f227f44d4d0231009b38a601aafd5175f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
